creyD/prettier_action

README.md

- Remove the distinction between running on pull requests and branches. When always using `${{ github.head_ref }}`, this action works fine for both.
- Use checkout action v2
- Omit `GITHUB_TOKEN`, it works fine without passing it explicitly
Thanks for the action, it has been working great for me.

Simplify configuration example

---

README.md
action.yml
entrypoint.sh

closes https://github.com/creyD/prettier_action/issues/16
Let me know if the implementation makes sense :). I wasn't really sure what the easiest way to test the implementation was though, so I didn't verify whether it works yet.

feat: allow action to use current commit instead of creating a new one

---

entrypoint.sh

I think something went wrong with merging some conflicts in dev branch, the INPUT_SAME_COMMIT logic was placed in the else of the `git add` logic in the entrypoint.sh. At least, I didn't intend for that. 
It meant that if you set same_commit to true, that it wouldn't add the changed files to staged, so the prettier changes wouldn't be committed. I moved it below the add logic now.
I tested it here: https://github.com/jorenbroekema/prettier-action-test/commit/914ad3425ab718a3a96f8df125f1f7e78803d8c9
That commit was first only including package.json and ci.yml. After pushing that to master, the CI amended the commit and prettified the `foo.js`. Looks good to me now :)

fix: add commit and push logic after git add logic

---

README.md

I found that `only_changed` was available in v3.1 so the README for me was misleading as found here https://github.com/EddieJaoudeCommunity/awesome-github-profiles/pull/175
Overall though - Cool action @creyD 👍🏻

Bump version of README to `prettier_action@v3.1`

---

README.md

Since the parameter was removed in https://github.com/creyD/prettier_action/releases/tag/v3.0, there is no need to document it.

Remove branch parameter from docs

---

action.yml
entrypoint.sh

This will allow users to specify a list of plugins to add before running prettier on their files. I have used this on [Volcano](https://github.com/sebastianks/volcano) more specifically [here](https://github.com/sebastianks/volcano/blob/next/.github/workflows/prettier.yml)
Closes #22

Feature add plugins

---

README.md
action.yml

The entrypoint script checks for correctly named Prettier plugins on [lines 44–45](https://github.com/creyD/prettier_action/blob/master/entrypoint.sh#L44-L45), but the description in the config file and README are not consistent.
This updates those references to clarify how plugins should be specified.

Fix plugin name syntax in README & description

---

entrypoint.sh

The previous system relied on a different shell's magic for handling `*` / `**`
nullglob
- If set, Bash allows filename patterns which match no files to expand to a null string, rather than themselves.
globstar
- If set, the pattern ‘**’ used in a filename expansion context will match all files and zero or more directories and subdirectories. If the pattern is followed by a ‘/’, only directories and subdirectories match.

Handle bash globs

---

README.md
entrypoint.sh

Fixes _Issue #37 [BUG] Dry run reporting unpretty files when all files match styles_ by adding a verification of shell command output  for prettier and verifying it status code in case it is a dry-run, handling it properly.

Fixes Issue #37 [BUG] Dry run reporting unpretty files when all files match styles

---

README.md
action.yml
entrypoint.sh

This adds the option `push_options` for adding git push args.

Add input git push options

---

README.md
action.yml
entrypoint.sh

This PR adds the option `github_token` to override the default token used to push the changes.
Fixes #55.

Add support to override the default github token

---

action.yml
entrypoint.sh

Hi, I've tried to use the branch `dev` in a personal project and I've found some issues throughout the process.
This PR is an attempt to fix these issues. If you think it's better to split into multiple PRs, please, let me know.
---
**Problem 1**: Missing environment variable `INPUT_GITHUB_TOKEN` even when the parameter `github_token` is set
I've added this env var following the same pattern used for the other ones.
---
**Problem 2**: Several errors are printed when prettier doesn't run successfully
i.e.
```bash
Error:  No parser and no file path given, couldn't infer a parser.
Problem running prettier with --write **/*.{ts,tsx,js,json,md}
rm: cannot remove 'node_modules/': No such file or directory
No node_modules/ folder.
fatal: ambiguous argument 'package-lock.json': unknown revision …
```

Small fixes for branch dev

---

entrypoint.sh

`git reset --hard <file>` doesn't work - so package-lock.json is always deleted.
Using `git checkout -- package-lock.json` instead seems reasonable.

Don't delete package-lock.json

---

README.md

`main` is now the default branch name: https://github.com/github/renaming#new-repositories-use-main-as-the-default-branch-name
Update the examples in the docs to reflect this

Use 'main' instead of 'master' for examples

---

entrypoint.sh

Fixed the issue where the `only_changed` option does not work when the file name contains a space

handle space in file name

---

entrypoint.sh

Resolves #74.
https://github.com/insyri/prettier_action/commit/a9474e2eb85c58c44fed4cf41e4d856e3ba1d42e
The issue was the shell syntax was wrong, I previously attempted to implement an inline if statement inside the string, this changes to a variable input inside the string that is determined to be nothing or the message input via an outside determiner.
Apologies for the delayed fix.

Fix for #74

---

README.md

Update the examples so first time users don't experience the bug that was fixed by https://github.com/creyD/prettier_action/commit/26c489217918dbfb2f743734285e8cacf3960d88

Update examples to use 4.1.1 instead of 4.1

---

entrypoint.sh

This fixes a problem where `@prettier/plugin-ruby` was not being used.
Config:
```yaml
prettier:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
with:
ref: ${{ github.head_ref }}
- uses: creyD/prettier_action@v4.1.1
with:
prettier_plugins: "@prettier/plugin-ruby"
prettier_options: "--write ."
```
**Before:**
**After:**

fix(Plugin): don't install plugins globally

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
README.md
entrypoint.sh

- Plugins now don't get installed globally (Thanks @seven1m)
- Fixed #78 (Thanks @bercos)

Minor Feature & Bugfix Update

---

README.md

actions/checkout@v2 uses node12. GitHub gives a deprecation warning for this since node12 is out of support. actions/checkout@v3 uses node16 by default.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12
closes #103

Bumped actions/checkout to v3 in examples

---

action.yml

This action is failing with the latest Ubuntu 22.04 image because npm updated to v9 which doesn't have the `bin` command. This change has fixed it for our repositories that are using the ubuntu image with npm v9

Don't use the npm bin command to resolve the bin path

---

entrypoint.sh

When the only change made in a commit is to make the file "unpretty", running prettier on top will cause the amended commit to be empty. This throws an exception unless the --allow-empty flag is set on the git command

Allow amended commits to be empty

---

README.md
action.yml
entrypoint.sh

Fixes #80
and allows commit and push of different steps to be combined in single commit and push.

Support not exiting the process in case of changes in dry mode

---

README.md
action.yml
entrypoint.sh

I want to have the following behavior:
- A workflow triggers the `prettier_action`. 
- The `prettier_action` makes prettier changes and commits them back to the PR branch.
- Workflows re-run on the prettified changes, verifying the prettified changes.
The prettier changes [don't re-trigger workflow execution](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
), because the user is set to the Actions user. 
This PR adds an option to use the author's identity, so a user can re-trigger workflows.
I tested this against a private pipeline that I operate, and it worked.

feat: Allow overriding actor

---

entrypoint.sh

Something about 473978add96e87010e65ca5897a8d16d18df9ce8 broke prettier_action for us.  Even though everything looks right for `$INPUT_WORKING_DIRECTORY` to have a default value, so `cd "$INPUT_WORKING_DIRECTORY"` should be fine, in our usage `$INPUT_WORKING_DIRECTORY` was consistently empty.  This had a practical side effect of reporting that prettier wasn't found (because we are setting our PATH based off of `$GITHUB_ACTION_PATH`).  Adding internal default of `$GITHUB_ACTION_PATH` fixed it.  I'm happy to work with you to determine why this isn't getting set in our environment, but I ran out of things to check

set INPUT_WORKING_DIRECTORY if not already set

---

action.yml
entrypoint.sh

This PR includes the changes for #134.  If that PR changes significantly or is rejected, this PR will need to be reworked
This PR adds new option `only_changed_pr`.  This behaves similarly to `only_changed`, except instead of only considering files which were modified in the last commit, this option only considers files which were modified in any commit included in the current PR.

Add only_changed_pr

---

README.md
action.yml
entrypoint.sh

- Added option no_commit
- Default working directory is now the github.action_path
- Set prettier_version default to latest
- Added option only_changed_pr
- Added option git_identity

Different minor changes
